language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.html)|^(LICENSE)|^(docs)|(.github)'
      then
        echo "Only docs were updated, not running CI!"
        travis_terminate 0
      fi

install:
    - yarn install --frozen-lockfile

jobs:
  include:
    - stage: Check types
      name: Check types
      script: yarn check-types
      
    - stage: Lint
      name: Lint
      script: yarn lint
      
    - stage: Test
      name: Test
      script: yarn test
